# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31341c2d7c4e0ee35af4303ccb7844a56e65f8b94459d20018f62ddc2b3a2d824ba302102046559d61c6413753f3de106b0423e23b6f0f89f150e6d2fcf54ab9

test:
  secret_key_base: c8796acc0b638d279fc303306d4cf368b1e1537b77b8672d8925f34c2484f6cf251c4c4cd3e8f124b1e20483d6572902c518b2e2135e733c7dead1f48ff2bf65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
